### ISSUE TITLE
Tests fail on Strawberry Perl 5.24.1.1 (64bit) Windows 10

### ISSUE THREAD

**Issue by jfroebe** [xsawyerx/sys-hostip#16]
Platform: Strawberry Perl 5.24.1.1 (64bit) Windows 10
Sys::HostIP version: 2.0000

[sys-hostip_test_failure.txt.txt](https://github.com/xsawyerx/sys-hostip/files/900035/sys-hostip_test_failure.txt.txt)

**Comment by paultcochrane** [comment]
Hi @jfroebe thanks for the report!  This should have been fixed in a recent commit that hasn't yet made it into a release.  However, just to check, would it be ok if you also sent the output of `ipconfig.exe`?

**Comment by jfroebe** [comment]
No problem 😊

 

jason

 

Microsoft Windows [Version 10.0.14393]

(c) 2016 Microsoft Corporation. All rights reserved.

 

C:\Users\jason>ipconfig

 

Windows IP Configuration

 

 

Ethernet adapter Ethernet:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Ethernet adapter Local Area Connection* 15:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Wireless LAN adapter Local Area Connection* 2:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Ethernet adapter VMware Network Adapter VMnet1:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::1435:48a0:93d7:630b%8

   IPv4 Address. . . . . . . . . . . : 192.168.81.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Ethernet adapter VMware Network Adapter VMnet8:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::bde4:8ad6:37c4:92cc%12

   IPv4 Address. . . . . . . . . . . : 192.168.248.1

   Subnet Mask . . . . . . . . . . . : 255.255.255.0

   Default Gateway . . . . . . . . . :

 

Wireless LAN adapter Wi-Fi:

 

   Connection-specific DNS Suffix  . :

   Link-local IPv6 Address . . . . . : fe80::20fc:f224:5da6:428c%7

   IPv4 Address. . . . . . . . . . . : 172.21.224.239

   Subnet Mask . . . . . . . . . . . : 255.255.240.0

   Default Gateway . . . . . . . . . : 172.21.239.254

 

Tunnel adapter isatap.{235D6400-AFF9-4ED8-88E3-F31BCCEC1007}:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Tunnel adapter Local Area Connection* 5:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Tunnel adapter isatap.{4D0BD8ED-0489-4F86-8CA4-CE82B4D6F223}:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

 

Tunnel adapter isatap.{2F9F4946-1F16-4897-8AC0-E80FD8F38D21}:

 

   Media State . . . . . . . . . . . : Media disconnected

   Connection-specific DNS Suffix  . :

**Comment by paultcochrane** [comment]
@jfroebe awesome!  Thanks :-)  It's also just as I thought: in the code in 2.000 and below the assumption is made that "Local Area Connection" is the default interface.  This then makes the call to the `ip()` method fail and hence the failure of the `base.t` tests.  A workaround has already been pushed to `master`, however atm I can't push a new version to CPAN.

@xsawyerx could you do a bugfix release if you get the time please?

Due to other commitments I won't be able to do any more work on this until after Easter, so if nothing has happened until then, just ping me and we'll get a new version out.

**Comment by pwr22** [comment]
@paultcochrane @xsawyerx any chance this could get released? We've just hit a Windows compatibility issue at work so we're having to roll our own version of this module now 😢 

We'd be super happy if we could switch back to pulling the CTAF release directly 😄

**Comment by paultcochrane** [comment]
@pwr22 sure!  I just need to prod @xsawyerx to cut the release ;-)

**Comment by paultcochrane** [comment]
Hi @pwr22 and @jfroebe.  @xsawyerx has released a new version to CPAN so hopefully this fixes this issue for you.  Could you give us a quick heads up if this has done the job or not?

**Comment by paultcochrane** [comment]
This has been out in the wild for a year now, so I hope it's ok to close this issue now. If not, please reopen. :-)
