### ISSUE TITLE
Fails when /sbin/ifconfig is not installed

### ISSUE THREAD

**Issue by andk** [xsawyerx/sys-hostip#17]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/9e04e0f6-f073-11e8-9ae5-ed24b333af3f

**Comment by paultcochrane** [comment]
My guess is that this is related to #5, since if `ifconfig` isn't installed on Linux, then `ip` should be.  We still need to implement the fallback to `ip` if `ifconfig` doesn't exist.

**Comment by paultcochrane** [comment]
@andk I've just merged a patch to fix the issue.  @xsawyerx I've also updated the Changes file; would you be able to cut a release please?  I'd cut it for you, but I don't have COMAINT ;-)

**Comment by paultcochrane** [comment]
Since this has been fixed in master and there has been a new release, I'm closing this issue.  Many thanks for reporting it!
